name: Python Test

on:
  push:
    branches:
      - main

jobs:
  test:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Run tests
        run: |
          python -m unittest discover
